version: "3.8"

services:
  app:
    build:
      context: .
      
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000 && flake8"
    environment:
      - DB_HOST=db
      - DB_NAME=onlinemarket
      - DB_USER=onlinemarket
      - DB_PASS=superusersecret

  db:
    image: postgres:10-alpine
    restart: always
    environment:
      - POSTGRES_DB=onlinemarket
      - POSTGRES_USER=onlinemarket
      - POSTGRES_PASSWORD=superusersecret

    ports:
      - "5432:5432"
