# Generated by Django 3.1.5 on 2021-01-08 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productowner',
            old_name='endereco',
            new_name='address',
        ),
    ]
