# Generated by Django 3.1.5 on 2021-01-11 09:52

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimage_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.company_image_file_path),
        ),
    ]
