# Generated by Django 3.1.5 on 2021-01-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210108_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='productowner',
            name='owner_type',
            field=models.CharField(choices=[('Particular', 'Particular'), ('Empresa', 'Empresa')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
