# Generated by Django 3.1.5 on 2021-01-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210111_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_new',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
